questions/urls.py
"""Urls for questions app"""
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('questions/', views.search, name='manage_questions'),
    path('questions/<int:pk>/details/', views.QuestionDetailsView.as_view(),
         name='question_details'),
    path('questions/add_new_question/', views.CreateQuestionView.as_view(),
         name='add_new_question'),
    path('questions/<int:pk>/edit_question/', views.EditQuestionView.as_view(),
         name='edit_question'),
    path('questions/delete_question/<int:pk>/', views.DeleteQuestionView.as_view(),
         name='delete_question'),
    path('questions/<int:pk>/toggle/', views.toggle_question_status,
         name='toggle_question'),
    path('questions/<int:pk>/add_option/', views.CreateOptionView.as_view(),
         name='add_option'),
    path('questions/<int:pk>/edit_option/', views.EditOptionView.as_view(),
         name='edit_option'),
    path('questions/<int:pk>/delete_option/', views.DeleteOptionView.as_view(),
         name='delete_option'),
    path('questions/<int:pk>/edit_question_text/',
         views.EditQuestionText.as_view(), name='edit_question_text'),
    path('questions/<int:pk>/edit_question_quiz/',
         views.EditQuestionQuiz.as_view(), name='edit_question_quiz'),
    path('questions/<int:pk>/edit_question_feedback/',
         views.EditQuestionFeedback.as_view(), name='edit_question_feedback'),
    path('questions/<int:pk>/edit_question_category/',
         views.EditQuestionCategory.as_view(), name='edit_question_category'),
    path('questions/<int:pk>/edit_question_image/',
         views.EditQuestionImage.as_view(), name='edit_question_image'),
]

quiz/urls.py
"""Urls for quiz app"""
from django.urls import path
from quiz import views

app_name = 'quiz'
urlpatterns = [
    path('', views.welcome_page_view, name='home'),
    path('quizzes/', views.QuizListView.as_view(), name='manage_quizzes'),
    path('quizzes/add_quiz/', views.CreateQuizView.as_view(), name='add_quiz'),
    path('quizzes/<slug:slug>/details/', views.QuizDetailsView.as_view(),
         name='quiz_details'),
    path('quizzes/<slug:slug>/edit_quiz/', views.EditQuizView.as_view(),
         name='edit_quiz'),
    path('quizzes/<slug:slug>/delete_quiz/', views.DeleteQuizView.as_view(),
         name='delete_quiz'),
    path('quizzes/<slug:slug>/toggle/', views.toggle_status, name='toggle'),
    path('quizzes/<slug:slug>/<int:pk>/remove_question/',
         views.remove_question_from_quiz, name='remove_question'),
    path('quizzes/<slug:slug>/<int:pk>/add_question/',
         views.add_question_to_quiz, name='add_question'),
    path('quizzes/add_category', views.AddCategoryInQuizView.as_view(),
         name='add_category_in_quiz'),
    # paths for views managing questions
    path('quizzes/<slug:slug>/add_question/',
         views.CreateQuestionInQuizView.as_view(),
         name='add_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_question/',
         views.DeleteQuestionInQuizView.as_view(),
         name='delete_question_in_quiz'),
    # paths for views for editing question elements when accessed from quiz
    path('quizzes/<slug:slug>/<int:pk>/edit_question/',
         views.EditQuestionInQuizView.as_view(), name='edit_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_text',
         views.EditQuestionText.as_view(), name='edit_question_text_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_quiz',
         views.EditQuestionQuiz.as_view(), name='edit_question_quiz_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_feedback',
         views.EditQuestionFeedback.as_view(),
         name='edit_question_feedback_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_category',
         views.EditQuestionCategory.as_view(),
         name='edit_question_category_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_image',
         views.EditQuestionImage.as_view(),
         name='edit_question_image_in_quiz'),
    # paths for viees managing options
    path('quizzes/<slug:slug>/<int:pk>/add_option/',
         views.CreateOptionInQuizView.as_view(), name='add_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_option/',
         views.EditOptionInQuizView.as_view(), name='edit_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_option/',
         views.DeleteOptionQuizView.as_view(), name='delete_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/details/',
         views.QuestionDetailsInQuizView.as_view(),
         name='quiz_question_details'),
    ]

teaze/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('quiz.urls'), name='quiz_urls'),
    path('', include('results.urls'), name='results_urls'),
    path('', include('questions.urls'), name='questions_urls'),
    path('', include('categories.urls'), name='categories_urls'),
]

questions/views.py
"""Question app views."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect,
    HttpResponseRedirect,
)
from django.urls import reverse_lazy
from django.views.generic import CreateView
# views provided by django-bootstrap-modal-forms
from bootstrap_modal_forms.generic import (
    BSModalReadView,
    BSModalCreateView,
    BSModalUpdateView,
    BSModalDeleteView
)
from quiz.models import Quiz
from results.models import Answer
from .filters import QuestionFilter
from .forms import (
    NewQuestionForm,
    NewOptionForm,
    EditQuestionTextForm,
    EditQuestionFeedbackForm,
    EditQuestionQuizForm,
    EditQuestionCategoryForm,
    EditQuestionImageForm
)
from .models import Question, Option


class CreateQuestionView(CreateView):
    """Add new question independently view"""
    template_name = 'questions/add_new_question.html'
    form_class = NewQuestionForm
    success_message = 'Question created successfully.'

    def get(self, *args, **kwargs):
        """Override get method to grab quiz."""
        form = self.form_class
        slug = self.kwargs.get('slug')

        context = {
            'form': form,
            'slug': slug,
        }

        return render(self.request, self.template_name, context)

    def post(self, *args, **kwargs):
        """Override the default post method"""
        user = self.request.user
        form = self.form_class(self.request.POST, self.request.FILES)
        slug = self.kwargs.get('slug')
        if form.is_valid():
            # create object manually to post user as author
            # category added later using set() to avoid "Direct assignment
            # of many-to-many prohibited error."
            if self.kwargs.get('slug'):
                slug = self.kwargs.get('slug')
                quiz = get_object_or_404(Quiz, slug=slug)
                category = [quiz.category]
            else:
                quiz = form.cleaned_data.get('quiz')
                category = form.cleaned_data.get('category')

            body = form.cleaned_data.get('body')
            featured_image = form.cleaned_data.get('featured_image')
            feedback = form.cleaned_data.get('feedback')
            question = Question.objects.create(body=body, quiz=quiz,
                                               featured_image=featured_image,
                                               author=user, status=0,
                                               feedback=feedback)
            question.category.set(category)
            print(form.cleaned_data)
            return redirect(f'../{question.pk}/details/')
        else:
            print(form.errors)

        context = {
            'form': form,
            'slug': slug,
        }
        print(slug)
        return render(self.request, 'questions/add_new_question.html', context)


class CreateOptionView(LoginRequiredMixin, BSModalCreateView):
    """Create a new option for question."""

    form_class = NewOptionForm
    template_name = 'questions/add_option_modal.html'
    success_message = 'Option created successfully.'

    def get(self, *args, **kwargs):
        """
        Override get method to grab question and check existing
        options for 'is_correct'.
        """

        form = NewOptionForm()
        pk = self.kwargs.get('pk')
        question = get_object_or_404(Question, pk=pk)
        correct_options_count = question.correct_options_count

        context = {
            'form': form,
            'question': question,
            'correct_options_count': correct_options_count
        }

        return render(self.request, 'questions/add_option_modal.html', context)

    def post(self, *args, **kwargs):
        """Override default post method to include question info."""
        pk = self.kwargs.get('pk')
        question = get_object_or_404(Question, pk=pk)
        user = self.request.user
        form = NewOptionForm(self.request.POST)
        if form.is_valid():
            option_text = form.cleaned_data.get('option')
            is_correct = form.cleaned_data.get('is_correct')
            Option.objects.update_or_create(question=question,
                                            option=option_text,
                                            is_correct=is_correct, author=user)
            print(form.cleaned_data)
        return redirect('../details')


class QuestionDetailsView(LoginRequiredMixin, BSModalReadView):
    """Question details view."""
    model = Question
    template_name = 'questions/question_details_page.html'

    def get(self, request, *args, **kwargs):
        """Override the get method to pass in slug for redirection checks."""
        queryset = Question.objects.all()
        pk = self.kwargs.get('pk')
        question = get_object_or_404(queryset, pk=pk)
        options = question.options.all()
        quiz = None
        if self.kwargs.get('slug'):
            slug = self.kwargs.get('slug')
            quiz = get_object_or_404(Quiz, slug=slug)

        context = {
            'question': question,
            'options': options,
            'quiz': quiz,
        }
        return render(request, self.template_name, context)


class EditQuestionView(LoginRequiredMixin, BSModalUpdateView):
    """Edit question elements base class."""

    model = Question
    form_class = NewQuestionForm
    template_name = 'questions/edit_question_element_modal.html'
    success_message = 'Question updated successfully.'

    def get_success_url(self):
        pk = self.object.pk
        return reverse_lazy('questions:question_details', args=[pk])


# ---- Views to edit question elments ---
class EditQuestionText(EditQuestionView, BSModalUpdateView):
    """Edit the question's content."""

    form_class = EditQuestionTextForm


class EditQuestionQuiz(EditQuestionView, BSModalUpdateView):
    """Edit quiz assigned to the question."""

    form_class = EditQuestionQuizForm


class EditQuestionFeedback(EditQuestionView, BSModalUpdateView):
    """Edit question feedback."""

    form_class = EditQuestionFeedbackForm


class EditQuestionCategory(EditQuestionView, BSModalUpdateView):
    """Edit categories assigned to the question."""

    form_class = EditQuestionCategoryForm


class EditQuestionImage(EditQuestionView, BSModalUpdateView):
    """Edit image assigned to the question."""

    form_class = EditQuestionImageForm


class EditOptionView(LoginRequiredMixin, BSModalUpdateView):
    """Edit options."""

    model = Option
    template_name = 'questions/edit_option.html'
    form_class = NewOptionForm
    success_message = 'Option updated successfully.'

    def get_success_url(self, *args, **kwargs):
        pk = self.object.question.pk
        return reverse_lazy('questions:question_details', args=[pk])


class DeleteQuestionView(LoginRequiredMixin, BSModalDeleteView):
    """Delete question."""

    model = Question
    template_name = 'questions/question_confirm_delete.html'
    success_message = 'Question deleted successfully.'

    def get(self, *args, **kwargs):
        """Override the default get function."""
        pk = self.kwargs.get('pk')
        question = get_object_or_404(Question, pk=pk)
        protected = False
        protected_message = ''

        # Check if question exists in answers:
        # if yes, prevent deletion displaying message to the user,
        # if not, ask the user to confirm deletion.
        answers = Answer.objects.all()
        for answer in answers:
            if question == answer.question:
                protected_message = """This question appears in an
                assessments and cannot be deleted."""
                protected = True

        context = {
            'protected_message': protected_message,
            'protected': protected,
            'question': question,
        }
        return render(self.request, 'questions/question_confirm_delete.html',
                      context)

    def get_success_url(self, *args, **kwargs):
        """
        Change success url depending on whether
        accessed from quiz or question.
        """

        slug = self.kwargs.get('slug')
        print(slug)
        return reverse_lazy('questions:manage_questions')


class DeleteOptionView(LoginRequiredMixin, BSModalDeleteView):
    """Delete option."""
    model = Option
    template_name = 'questions/option_confirm_delete.html'
    success_message = 'Option deleted successfully.'

    def get(self, *args, **kwargs):
        """Override the default get function."""
        pk = self.kwargs.get('pk')
        option = get_object_or_404(Option, pk=pk)
        answers = Answer.objects.all()
        protected = False
        protected_message = ''

        # Check if question exists in answers:
        # if yes, prevent deletion displaying message to the user,
        # if not, ask the user to confirm deletion.
        for answer in answers:
            if answer.answer == option:
                protected_message = """This option appears in an
                assessments and cannot be deleted."""
                protected = True

        context = {
            'protected_message': protected_message,
            'protected': protected,
            'option': option,
        }
        return render(self.request, 'questions/option_confirm_delete.html',
                      context)

    def get_success_url(self, *args, **kwargs):
        pk = self.object.question.pk
        return reverse_lazy('questions:question_details', args=[pk])


def toggle_question_status(request, pk, *args, **kwargs):
    """Toggle question status between Draft (0) and Approved (1)."""
    question = get_object_or_404(Question, pk=pk)
    if question.status != 0:
        question.status = 0
    else:
        question.status = 1
    question.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# Code for checkting if filter is filled from:

questions/templates/questions/add_option_modal.html
{% load widget_tweaks %}
<!-- Form with question details that is being edited. -->
<form method="POST">
    {% csrf_token %}
    <div class="modal-header">
        <h3 class="modal-title">Add Option</h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <div class="modal-body">
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% for field in form %}
        <div class="form-group">
            {% if field.label == "Is correct" %}
            {% if correct_options_count < 1 %}
            <div class="d-flex flex-row my-1">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="mx-2">{% render_field field class="form-check-input" placeholder=field.label %}</div>
                {% else %}
                <div class="mt-1 text-smaller">Correct answer already exists.<br>Deselect current option to set this one
                    as correct.</div>
            </div>
            {% endif %}
            {% else %}
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            <div class="shadow">{% render_field field class="form-control" placeholder=field.label %}</div>
            {% endif %}
            <div class="{% if field.errors %} invalid{% endif %}">
                {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

questions/templates/questions/manage_questions.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<!-- Modal diplaying edit and delete forms -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<!-- Form goes here -->
		</div>
	</div>
</div>

<div class="container px-0 px-md-4 py-md-5" id="custom-cards">
	<div class="d-flex justify-content-between border-bottom">
		<div>
			<h2 class="pb-2">Questions</h2>
		</div>
		<h3 class="pb-2"><a href="{% url 'questions:add_new_question' %}" id="add-question"
				class="add-question text-dark linked">Add new<i class="fas fa-plus ms-1 ms-md-3"></i></a></h3>
	</div>
	<div>
		<!-- A href 'button' to toggle filter -->
		<div class="pt-2">
			<a class="btn-secondary p-1 m-2 ms-md-4 rounded collapsed border border-2 linked" data-bs-toggle="collapse" href="#collapseFilter"
				role="button" aria-expanded="false" aria-controls="collapseFilter">Show filter
				<i class="fas fa-filter ms-2"></i>
			</a>
			{% if has_filter %}
			<a href="{%  url 'questions:manage_questions' %}" class="btn-secondary p-1 m-4 rounded border border-2 linked">Clear filters</a>
			{% endif %}
		</div>
		<!-- Form with options for filtering -->
		<form method="get" class="collapse m-2 mt-3" id="collapseFilter">
			<div class="well shadow transparent-gray p-3">
				<h4 style="margin-top: 0">Filter</h4>
				<div class="row">
					<div class="form-group col-md-6">
						{{ filter.form.body.label_tag }}
						{% render_field filter.form.body class="form-control" %}
					</div>
					<div class="form-group col-md-3">
						{{ filter.form.quiz.label_tag }}
						{% render_field filter.form.quiz class="form-select" %}
					</div>
					<div class="form-group col-md-3">
						{{ filter.form.status.label_tag }}
						{% render_field filter.form.status class="form-select" %}
					</div>
					<div class="form-group col-md-11 m-1">
						{{ filter.form.category.label_tag }}
						<div>
							{% for choice in filter.form.category %}
							<label class="ms-3 checkbox-inline">
								{{ choice.tag }} {{ choice.choice_label }}
							</label>
							{% endfor %}
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-primary">
					<span class="glyphicon glyphicon-search"></span> Search
				</button>
			</div>
		</form>
	</div>
	<!-- Display a list of questions - all or filtered results -->
	<div class="row row-cols-1 row-cols-lg-2 align-items-stretch g-4 pt-3 mb-5">
		{% for question in filter.qs %}
		<div class="col">
			<!-- Check if question has image and add overlay if yes -->
			{% if 'placeholder' not in question.featured_image.url %}
			<div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg"
				style="background: url('{{ question.featured_image.url }}');">
				<div class="d-flex flex-column h-100 w-75 p-md-5 pb-3 text-white text-shadow-1 dark-overlay">
			{% else %}
			<div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg">
				<div class="d-flex flex-column h-100 p-md-5 pb-3 text-white text-shadow-1">
			{% endif %}
					<h5 class="modal-header">{{ question.body }}</h5>
						<div class="d-flex d-row align-items-center justify-content-between ">
							<a class="p-1 m-2 collapsed linked" data-bs-toggle="collapse" href="#collapseQ-{{question.pk}}"
								role="button" aria-expanded="false" aria-controls="collapseFilter">More...
							</a>
							<ul class="d-flex list-unstyled mt-auto justify-content-end">
								{% if question.quiz is None %}
								<li>
								<a data-form-url="{% url 'questions:delete_question' question.id %}"
										class="delete-question bs-modal linked" aria-label="Delete question" title="Delete">
										Delete<i class="fas fa-trash me-3 ms-2 fs-6"></i></a>
								</li>
								{% else %}
								<li>
								<a aria-label="Question cannot be deleted" class="linked text-decoration-line-through" data-bs-toggle="tooltip" data-bs-placement="right" title="Question used in quiz and cannot be deleted">
										Delete<i class="fas fa-exclamation-circle me-3 ms-2 fs-6"></i></a>
								</li>
								{% endif %}
								<li><a href="{% url 'questions:question_details' question.id %}" class="linked"
									 title="Details">
										View / edit
										<i class="fa fas fa-edit me-3 ms-2"></i></a>
								</li>
							</ul>
						</div>
							
						<div id="collapseQ-{{question.pk}}" class="collapse ms-3">
								<h6 class="card-title">
									{% if "," in question.get_categories %}Categories:{% else %}Category:{% endif %}<small>
										{{ question.get_categories }}</small></h6>
								<h6 class="card-title">Quizzes: <small>{{ question.quiz}}</small></h6>
								<h6 class="card-title">Status:
									<small>{% if question.status == 0 %}Draft{% else %}Approved{% endif %}</small></h6>
						</div>
				</div>	
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

questions/templates/questions/question_details_page.html
{% extends 'base.html' %}

{% block content %}

<!-- Modal to display delete view -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!-- Form goes here -->
        </div>
    </div>
</div>
<!-- Main Question details container -->
<div class="container">
    <div class="row m-md-5">
        <div class="col-lg-9 box-shadow m-auto transparent-gray">
            <div class="modal-header">
                <h3>Question details</h3>
                <!-- Cancel button-->
                <div>
                <!-- Change redirection depending on starting point -->
                    {% if quiz.slug %}
                    <a href="{% url 'quiz:quiz_details' quiz.slug %}" class="btn-close" aria-label="Close"></a>
                    {% else %}
                    <a href="{% url 'questions:manage_questions' %}" class="btn-close" aria-label="Close"></a>
                    {% endif %}
                </div>
            </div>
            <div class="me-3 d-flex align-items-center justify-content-end">
                <h5 class="m-1 ms-0 ms-2 p-1">Status:</h5>
                <a href="{% url 'questions:toggle_question' question.pk %}"
                    class="btn py-0">{% if question.status == 0 %}Draft{% else %}Approved{% endif %}</a>
            </div>
            <div class="d-flex my-2 m-md-2 p-1 align-items-baseline rounded bg-light shadow">
                <div class="m-1 p-1 w-100 rounded">
                    <h6 class="highlight rounded p-1">Question:</h6>
                    <h6 class="ms-2 my-0">{{ question.body }}</h6>
                </div>
                <div>
                    {% if quiz.slug %}
                    <a data-form-url="{% url 'quiz:edit_question_text_in_quiz' quiz.slug question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 ps-2 py-3 icon"></i></a></h4>
                    {% else %}
                    <a data-form-url="{% url 'questions:edit_question_text' question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 ps-2 py-3 icon"></i></a>
                    {% endif %}
                </div>
            </div>

            <div class="d-flex my-2 m-md-2 p-1 align-items-baseline rounded bg-light shadow">
                <div class="m-1 p-1 w-100 rounded">
                    <h6 class="highlight rounded p-1">Question feedback:</h6>
                    <h6 class="flex-grow-1">
                        {% if question.feedback %}{{ question.feedback }}{% else %}Not provided{% endif %}</h6>
                </div>
                <div>
                    {% if quiz.slug %}
                    <a data-form-url="{% url 'quiz:edit_question_feedback_in_quiz' quiz.slug question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 icon"></i></a>
                    {% else %}
                    <a data-form-url="{% url 'questions:edit_question_feedback' question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 icon"></i></a>
                    {% endif %}
                </div>
                <div class="m-1 p-1 w-100 rounded border-start">
                    <h6 class="ms-2 p-1 highlight rounded">Image:</h6>
                    {% if 'placeholder' not in question.featured_image.url %}
                    <img src="{{ question.featured_image.url }}" class=" img-thumbnail" alt="question featured image">
                    {% else %}
                    <h6 class="ms-2 my-0 flex-grow-1">None</h6>
                    {% endif %}
                </div>
                <div>
                    {% if quiz.slug %}
                    <a data-form-url="{% url 'quiz:edit_question_image_in_quiz' quiz.slug question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 pe-2 icon"></i></a>
                    {% else %}
                    <a data-form-url="{% url 'questions:edit_question_image' question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 pe-2 icon"></i></a>
                    {% endif %}
                </div>
            </div>
            <div class="d-flex flex-col my-2 m-md-2 p-1 align-items-baseline rounded bg-light shadow">
                <div class="m-1 p-1 w-100 rounded">
                    <h6 class="p-1 highlight rounded">Quiz:</h6>
                    <h6 class="my-0 flex-grow-1">{{ question.quiz }}</h6>
                </div>
                <div>
                    {% if quiz.slug %}
                    <a data-form-url="{% url 'quiz:edit_question_quiz_in_quiz' quiz.slug question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 icon"></i></a>
                    {% else %}
                    <a data-form-url="{% url 'questions:edit_question_quiz' question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 icon"></i></a>
                    {% endif %}
                </div>

                <div class="m-1 p-1 w-100 rounded border-start">
                    <h6 class="ms-2 p-1 highlight rounded">{% if "," in question.get_categories %}Categories:{% else %}
                        Category:{% endif %}</h6>
                    <h6 class="ms-2 flex-grow-1">{{ question.get_categories }}</h6>
                </div>
                <div>
                    {% if quiz.slug %}
                    <a data-form-url="{% url 'quiz:edit_question_category_in_quiz' quiz.slug question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 pe-2 icon"></i></a>
                    {% else %}
                    <a data-form-url="{% url 'questions:edit_question_category' question.pk %}" class="edit-question">
                        <i class="fas fa-edit mx-2 pe-2 icon"></i></a>
                    {% endif %}
                </div>
            </div>
            <ol class="modal-body m-md-3 bg-light shadow rounded">
                <li class="d-flex flex-row justify-content-between">
                    <h5 class="py-1"><small>Answer options:</small></h5>
                    <span>
                        <a data-form-url="{% url 'questions:add_option' question.pk %}" class="add-option bs-modal btn py-0"
                        title="Add option">Add new option</a>
                    </span>
                </li>
                {% for option in question.options.all %}
                <li class="d-flex m-2 p-2 ms-0 ps-4 rounded highlight">
                    <div class="flex-grow-1">{{ option.option }} {% if option.is_correct %}<span class="small text-muted">
                            (Correct)</span>{% endif %}</div>
                    <ul class="d-flex list-unstyled mt-auto justify-content-between">
                        <li><a data-form-url="{% if quiz.slug %}{% url 'quiz:edit_option_in_quiz' quiz.slug option.pk %}{% else %}{% url 'questions:edit_option' option.pk %}{% endif %}" class="edit-option bs-modal"
                                title="Edit">
                                <i class="fas fa-edit icon"></i></a></li>
                        <li>{% if quiz.slug %}
                            <a data-form-url="{% url 'quiz:delete_option_in_quiz' quiz.slug option.pk %}"
                                class="delete-option bs-modal" title="Delete option">
                                <i class="fas fa-trash ms-2 me-3 icon"></i></a>
                            {% else %}
                            <a data-form-url="{% url 'questions:delete_option' option.pk %}"
                                class="delete-option bs-modal" title="Delete option">
                                <i class="fas fa-trash ms-2 me-3 icon"></i></a>
                            {% endif %}
                        </li>
                    </ul>
                </li>
                {% endfor %}
                    
            </ol>
            {% if correct_option_counter > 1 %}
            <p class="fs-6 alert-danger">There are currently {{ correct_option_counter }} correct options. Only one option can be correct. Please correct the number of correct answers.</p>
            {% endif %}
            <div class="modal-footer">

                <div class="d-flex justify-content-md-end justify-content-sm-center">
                    {% if question.quiz %}
                        {% if quiz.slug %}
                        <a data-form-url="{% url 'quiz:edit_question_quiz_in_quiz' quiz.slug question.pk %}" class="edit-question btn">
                            To delete question, unassign it from quiz</a></a>
                        {% else %}
                        <a data-form-url="{% url 'questions:edit_question_quiz' question.pk %}" class="edit-question btn">
                            To delete question, unassign it from quiz</a>
                        {% endif %}
                    {% else %}
                    <a data-form-url="{% url 'questions:delete_question' question.pk %}"
                        class="delete-question btn">Delete</a>
                    {% endif %}
                        {% if quiz.slug %}
                        <a href="{% url 'quiz:quiz_details' quiz.slug %}" class="btn"
                                aria-label="Save">OK</a>
                        {% else %}
                        <a href="{% url 'questions:manage_questions' %}" class="btn"
                                aria-label="Save">OK</a>
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}