quiz/urls.py
"""Urls for quiz app"""
from django.urls import path
from quiz import views

app_name = 'quiz'
urlpatterns = [
    path('', views.welcome_page_view, name='home'),
    path('quizzes/', views.QuizListView.as_view(), name='manage_quizzes'),
    path('quizzes/add_quiz/', views.CreateQuizView.as_view(), name='add_quiz'),
    path('quizzes/<slug:slug>/details/', views.QuizDetailsView.as_view(),
         name='quiz_details'),
    path('quizzes/<slug:slug>/edit_quiz/', views.EditQuizView.as_view(),
         name='edit_quiz'),
    path('quizzes/<slug:slug>/delete_quiz/', views.DeleteQuizView.as_view(),
         name='delete_quiz'),
    path('quizzes/<slug:slug>/toggle/', views.toggle_status, name='toggle'),
    path('quizzes/<slug:slug>/<int:pk>/remove_question/',
         views.remove_question_from_quiz, name='remove_question'),
    path('quizzes/<slug:slug>/<int:pk>/add_question/',
         views.add_question_to_quiz, name='add_question'),
    path('quizzes/add_category', views.AddCategoryInQuizView.as_view(),
         name='add_category_in_quiz'),
    # paths for views managing questions
    path('quizzes/<slug:slug>/add_question/',
         views.CreateQuestionInQuizView.as_view(),
         name='add_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_question/',
         views.DeleteQuestionInQuizView.as_view(),
         name='delete_question_in_quiz'),
    # paths for views for editing question elements when accessed from quiz
    path('quizzes/<slug:slug>/<int:pk>/edit_question/',
         views.EditQuestionInQuizView.as_view(), name='edit_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_text',
         views.EditQuestionText.as_view(), name='edit_question_text_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_quiz',
         views.EditQuestionQuiz.as_view(), name='edit_question_quiz_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_feedback',
         views.EditQuestionFeedback.as_view(),
         name='edit_question_feedback_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_category',
         views.EditQuestionCategory.as_view(),
         name='edit_question_category_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_image',
         views.EditQuestionImage.as_view(),
         name='edit_question_image_in_quiz'),
    # paths for viees managing options
    path('quizzes/<slug:slug>/<int:pk>/add_option/',
         views.CreateOptionInQuizView.as_view(), name='add_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_option/',
         views.EditOptionInQuizView.as_view(), name='edit_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_option/',
         views.DeleteOptionQuizView.as_view(), name='delete_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/details/',
         views.QuestionDetailsInQuizView.as_view(),
         name='quiz_question_details'),
    ]

results/urls.py
"""Urls for results app"""
from django.urls import path
from . import views

app_name = 'results'
urlpatterns = [
    path('quizzes/<slug:slug>/take_quiz/', views.TakeQuizView.as_view(),
         name='take_quiz'),
    path('quizzes/<slug:slug>/assessment-<int:pk>/results/',
         views.AssessmentView.as_view(), name='assessment_details'),
    ]

teaze/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('quiz.urls'), name='quiz_urls'),
    path('', include('results.urls'), name='results_urls'),
    path('', include('questions.urls'), name='questions_urls'),
    path('', include('categories.urls'), name='categories_urls'),
]

quiz/models.py
"""Quiz model and methods"""
from django.urls import reverse
from django.db import models
from django.template.defaultfilters import slugify
from cloudinary.models import CloudinaryField
from categories.models import Category
# import random


STATUS = ((0, 'Draft'), (1, 'Published'))


class Quiz(models.Model):
    """Create Quiz object"""

    title = models.CharField(max_length=200, unique=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT,
                                 related_name='quiz')
    slug = models.SlugField(max_length=200, unique=True)
    description = models.CharField(max_length=300, blank=True)
    # number_of_questions = models.IntegerField()
    featured_image = CloudinaryField('image', default='placeholder',
                                     blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        """Set plural name to show in admin"""
        verbose_name_plural = "Quizzes"

    def get_questions(self):
        """Get all questions assigned to thie quiz"""
        # Randomisation of quesitons taken from Pyplane tutorial:
        # https://www.youtube.com/watch?v=T9xOjVJI1rg
        # questions = list(self.questions.all())
        # random.shuffle(questions)
        # return questions[:self.num_of_questions]
        return self.questions.all()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Quiz, self).save(*args, **kwargs)

    def __str__(self):
        """Quiz string method"""
        return self.title

    def toggle_status(self, *args, **kwargs):
        """"Togge quiz status."""
        if self.status != 0:
            self.status = 0
        else:
            self.status = 1
        self.save()
        super(Quiz, self).save(*args, **kwargs)

    def get_absolute_url(self):
        """Get absolute url"""
        return reverse('quiz:quiz_details', kwargs={"slug": self.slug})

quiz/forms.py
"""Forms for quiz app"""
from django import forms
from bootstrap_modal_forms.mixins import (
    PopRequestMixin,
    CreateUpdateAjaxMixin
)
from questions.models import Question
from .models import Quiz


class NewQuizForm(forms.ModelForm):
    """Form to create new quiz."""

    STATUS = ((0, 'Draft'), (1, 'Published'))

    class Meta:
        """Meta class specifying fields."""
        model = Quiz
        fields = (
            'title',
            'category',
            'description',
            'featured_image',
        )

        widgets = {
            'title': forms.TextInput,
            'category': forms.Select,
            'description': forms.Textarea(attrs={'rows': 3}),
        }


class AddQuestionToQuizForm(forms.ModelForm):
    """Question form class to use when adding from the quiz."""

    STATUS = ((0, 'Draft'), (1, 'Published'))

    class Meta:
        """Specify fields to use AddQuestionToQuizForm"""
        model = Question
        fields = (
            'body',
            'feedback',
        )


class ToggleQuizStatusForm(PopRequestMixin,
                           CreateUpdateAjaxMixin,
                           forms.ModelForm):
    """Form to create new quiz."""

    STATUS = ((0, 'Draft'), (1, 'Published'))

    class Meta:
        """Meta class specifying fields."""
        model = Quiz
        fields = (
            'status',
        )

quiz/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect,
    HttpResponseRedirect
    )
from django.views import generic
# views provided by django-bootstrap-modal-forms
from bootstrap_modal_forms.generic import (
    BSModalCreateView,
    BSModalUpdateView,
)
from categories.models import Category
from categories.forms import NewCategoryForm
from questions.forms import (
    EditQuestionTextForm,
    EditQuestionFeedbackForm,
    EditQuestionQuizForm,
    EditQuestionCategoryForm,
    EditQuestionImageForm,)
from questions.models import Question
from questions.views import (
    CreateOptionView,
    CreateQuestionView,
    DeleteOptionView,
    DeleteQuestionView,
    EditOptionView,
    EditQuestionView,
    QuestionDetailsView,
    )
from results.models import Assessment
from .models import Quiz
from .forms import (
    NewQuizForm,
    AddQuestionToQuizForm,
)


def welcome_page_view(request):
    """Landing page - view for the index.html"""

    quiz_draft_count = Quiz.objects.filter(status=0).count()
    quiz_published_count = Quiz.objects.filter(status=1).count()
    question_draft_count = Question.objects.filter(status=0).count()
    question_published_count = Question.objects.filter(status=1).count()
    categories_count = Category.objects.all().count()
    assessment = None
    completed_quizzes = []

    if request.user.groups.filter(name='Admin').exists():
        quiz_list = Quiz.objects.order_by('-created_on')
    else:
        quiz_list = Quiz.objects.filter(status=1).order_by('-created_on')

    if request.user.is_authenticated:
        assessments = Assessment.objects.filter(user=request.user)
        for assessment in assessments:
            completed_quizzes.append(assessment.quiz)
            assessment = assessment
    else:
        return redirect('account_login')

    context = {
        'quiz_draft_count': quiz_draft_count,
        'quiz_published_count': quiz_published_count,
        'question_draft_count': question_draft_count,
        'question_published_count': question_published_count,
        'categories_count': categories_count,

        'completed_quizzes': completed_quizzes,
        'quiz_list': quiz_list,
        'assessment': assessment
    }
    return render(request, 'index.html', context)


# Add, Edit and display quizzes views
class CreateQuizView(LoginRequiredMixin, generic.CreateView):
    """Create new quiz."""

    template_name = 'quiz/add_quiz.html'
    form_class = NewQuizForm
    success_message = 'Quiz created successfully.'

    def get_success_url(self):
        slug = self.object.slug
        return reverse_lazy('quiz:quiz_details', args=[slug])


class EditQuizView(LoginRequiredMixin, generic.UpdateView):
    """Edit quiz"""
    template_name = 'quiz/edit_quiz.html'
    form_class = NewQuizForm
    queryset = Quiz.objects.all()


class DeleteQuizView(LoginRequiredMixin, generic.DeleteView):
    """Delete quiz"""
    queryset = Quiz.objects.all()
    template = 'quiz/delete_quiz.html'
    success_url = reverse_lazy('quiz:manage_quizzes')


class QuizListView(LoginRequiredMixin, generic.ListView):
    """Display list of quizzes depending on type of user."""
    model = Quiz
    template_name = 'quiz/manage_quizzes.html'

    def get(self, request, *args, **kwargs):
        """Overwrite get method"""
        if request.user.groups.filter(name='Admin').exists():
            quiz_list = Quiz.objects.order_by('-created_on')
        else:
            quiz_list = Quiz.objects.filter(status=1).order_by('-created_on')

        if request.user.is_authenticated:
            assessments = Assessment.objects.filter(user=request.user)
            completed_quizzes = []
            for assessment in assessments:
                completed_quizzes.append(assessment.quiz)

            return render(request, self.template_name, {
                'completed_quizzes': completed_quizzes,
                'assessments': assessments,
                'quiz_list': quiz_list,
                }
            )
        else:
            return redirect('account_login')


class QuizDetailsView(LoginRequiredMixin, generic.DetailView):
    """Quiz details view."""

    template_name = 'quiz/quiz_detail.html'

    def get(self, *args, **kwargs):
        """Overwrite the default get function to render available qustions
        with the same category."""

        slug = self.kwargs.get('slug')
        quiz = get_object_or_404(Quiz, slug=slug)

        quiz_category = quiz.category
        questions = Question.objects.all()

        available_questions = []
        for question in questions:
            question_categories = question.get_categories()
            if str(quiz_category) in question_categories and question.quiz is None:
                available_questions.append(question)
        context = {
            'quiz': quiz,
            'available_questions': available_questions,
            'slug': slug,
        }

        return render(self.request, self.template_name, context)


def toggle_status(request, slug, *args, **kwargs):
    """"Togge quiz status."""
    quiz = get_object_or_404(Quiz, slug=slug)
    if quiz.status == 0:
        messages.warning(request, """
        Quiz has been set as Approved. It is now accessible
         to test takers.""")
    else:
        messages.success(request, 'Quiz status changed to Draft.')
    quiz.toggle_status()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def remove_question_from_quiz(request, pk, *args, **kwargs):
    """Remove question from the selected quiz. """

    question = get_object_or_404(Question, pk=pk)
    question.quiz = None
    question.save()
    messages.success(request, 'Question removed to quiz successfully.')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def add_question_to_quiz(request, pk, slug, *args, **kwargs):
    """Add question to the selected quiz."""

    quiz = get_object_or_404(Quiz, slug=slug)
    question = get_object_or_404(Question, pk=pk)
    question.quiz = quiz
    question.save()
    messages.success(request, 'Question added to quiz successfully.')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class AddCategoryInQuizView(LoginRequiredMixin, BSModalCreateView):
    """Add new category within add new quiz view."""

    template_name = 'categories/add_category.html'
    form_class = NewCategoryForm
    success_message = 'Success: Category was created.'
    success_url = reverse_lazy('quiz:add_quiz')


class CreateQuestionInQuizView(CreateQuestionView):
    """
    Add new question from quiz details view. Inherits from
     CreateQuestionView in questions app and changes the form.
    """
    form_class = AddQuestionToQuizForm


# Managing options while accessed from quiz view
class CreateOptionInQuizView(CreateOptionView):
    """Create a new option for question."""


class EditOptionInQuizView(EditOptionView):
    """Edit option while in quiz."""

    def get_success_url(self, *args, **kwargs):
        """Override success url from base class."""
        pk = self.object.question.pk
        slug = self.kwargs.get('slug')
        return reverse_lazy('quiz:quiz_question_details', args=[slug, pk])


class DeleteOptionQuizView(DeleteOptionView):
    """Delete option."""

    def get_success_url(self, *args, **kwargs):
        pk = self.object.question.pk
        slug = self.kwargs.get('slug')
        return reverse_lazy('quiz:quiz_question_details', args=[slug, pk])


class EditQuestionInQuizView(EditQuestionView):
    """Edit question when in detail view accessed from quiz."""

    def get_success_url(self, *args, **kwargs):
        """Override success url from base class."""
        slug = self.kwargs.get('slug')
        pk = self.kwargs.get('pk')
        return reverse_lazy('quiz:quiz_question_details', args=[slug, pk])


# ---- Views to edit question elments ---
class EditQuestionText(EditQuestionInQuizView, BSModalUpdateView):
    """Edit the question's content."""

    form_class = EditQuestionTextForm


class EditQuestionQuiz(EditQuestionInQuizView, BSModalUpdateView):
    """Edit quiz assigned to the question."""

    form_class = EditQuestionQuizForm


class EditQuestionFeedback(EditQuestionInQuizView, BSModalUpdateView):
    """Edit question feedback."""

    form_class = EditQuestionFeedbackForm


class EditQuestionCategory(EditQuestionInQuizView, BSModalUpdateView):
    """Edit categories assigned to the question."""

    form_class = EditQuestionCategoryForm


class EditQuestionImage(EditQuestionInQuizView, BSModalUpdateView):
    """Edit image assigned to the question."""

    form_class = EditQuestionImageForm


class DeleteQuestionInQuizView(DeleteQuestionView):
    """Delete question."""

    def get_success_url(self, *args, **kwargs):
        """Override success url from base class."""
        slug = self.kwargs.get('slug')
        return reverse_lazy('quiz:quiz_details', args=[slug])


class QuestionDetailsInQuizView(QuestionDetailsView):
    """View question details in quiz details view.
    Inherits from QuestionDetailView in question app with different path."""

quiz/templates/quiz/add_quiz.html
{% extends 'base.html' %}
{% load quiz_extras %}
{% load widget_tweaks %}

{% block content %}

<!-- Modal to display add category -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!-- Form goes here -->
        </div>
    </div>
</div>

<!-- Add quiz form -->
<div class="container mt-3">
    <div class="row">
        <div class="col-md-7 my-2 mb-5 mx-auto box-shadow transparent-gray">
            <!-- <form enctype="multipart/form-data" method="POST" action=""> -->
                <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-header">
                    <h3 class="modal-title">Add quiz</h3>
                    <!-- Cancel button -->
                    <a href="{% url 'quiz:manage_quizzes' %}" class="btn-close" aria-label="Close"></a>
                </div>
                <div class="modal-body">
                    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
                        {% for error in form.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <!-- Check if field is category and add button to add new category -->
                        {% if field.label == "Category" %}
                        <div class="d-flex flex-row shadow">{% render_field field class="form-select" %}
                        <a data-form-url="{% url 'quiz:add_category_in_quiz' %}" class="add-category" title="Add new category" aria-label="Add new category"><i class="fas fa-plus btn py-2"></i></a></div>
                        {% elif field.label == "Status" %}
                        <div class="shadow">{% render_field field class="form-select" %}</div>
                        {% elif field.label == "Image" %}
                        <div class="shadow">{% render_field field class="form-control" %}</div>
                        {% else %}
                        <div class="shadow">{% render_field field class="form-control" placeholder=field.label %}</div>
                        {% endif %}
                        <div class="{% if field.errors %} invalid{% endif %}">
                            {% for error in field.errors %}
                            <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %} 
                </div>
                <!-- Form footer -->
                <div class="modal-footer m-auto">
                    <div class="m-auto">
                        <a href="{% url 'quiz:manage_quizzes' %}" class="btn">Cancel</a>
                        <button type="submit" class="btn" aria-label="Save">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

quiz/templates/quiz/manage_quizzes.html
{% extends 'base.html' %}
{% load quiz_extras %}
{% load widget_tweaks %}

{% block content %}

<!-- Modal to display delete view -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!-- Form goes here -->
        </div>
    </div>
</div>
<!-- Main content -->
<div class="container px-0 px-md-4 py-md-5 mt-3 mb-5" id="custom-cards">
    <!-- Page header and add new quiz button -->
    <div class="d-flex justify-content-between border-bottom">
        <div>
            <h2 class="pb-2">Quizzes</h2>
        </div>
        <div class="me-3">
            <h3 class="pb-2"><a href="{% url 'quiz:add_quiz' %}" alt="Add category" class="text-dark linked">Add new<i class="fas fa-plus ms-1 ms-md-3"></i></a></h3>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-lg-2 align-items-stretch g-4 py-md-5">
        {% for quiz in quiz_list %}
        <div class="col pt-2">
            {% if 'placeholder' not in quiz.featured_image.url %}
            <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg"
                style="background: url('{{quiz.featured_image.url}}');">
                <div class="d-flex flex-column h-100 w-75 p-2 p-md-5 text-white text-shadow-1 dark-overlay">
            {% else %}
            <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg">
                <div class="d-flex flex-column h-100 p-2 p-md-5 text-white text-shadow-1">
            {% endif %}
                            <div class="modal-header">
                                <h5 class="">{{ quiz.title }}</h5><a
                                    data-form-url="{% url 'quiz:delete_quiz' quiz.slug %}" class="delete-quiz linked"
                                    aria-label="Delete" title="Delete"><i class="fas fa-trash me-3 ms-2"></i></a>
                            </div>
                            <div class="modal-body">
                                <p class="fs-6">{{ quiz.description }}</p>
                                <h6 class="card-title">Category: <small>{{ quiz.category }}</small></h6>
                                <h6 class="card-title">Number of questions: <small>{{ quiz.questions.count }}</small>
                                </h6>
                                <ul class="d-flex list-unstyled mt-4 mb-2 justify-content-end">
                                    <li><a href="{% url 'quiz:quiz_details' quiz.slug %}" class="linked" alt="Details"
                                            title="Details">View / edit<i
                                                class="fas fas fa-edit me-3 ms-2"></i></a></li>
                                    <li><a href="{% url 'results:take_quiz' quiz.slug %}" class="linked"> Preview</a><i
                                            class="fas fa-search me-3 ms-2"></i></li>

                                </ul>
                            </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

                
{% endblock %}

quiz/templates/quiz/quiz_confirm_delete.html
{% load widget_tweaks %}
<!-- Form with category details -->
<form method="post">
  {% csrf_token %}
  <!-- Modal content injected into the modal div in the main manage categories view  -->
  <div class="modal-header">
    <h3 class="modal-title">Delete quiz</h3>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <div class="modal-body">
    <p>Are you sure you want to delete <strong>{{ quiz.title }}</strong>? This action cannot be undone.</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn">Delete</button>
  </div>
</form>

quiz/templates/quiz/quiz_detail.html
{% extends 'base.html' %}
{% load quiz_extras %}
{% block content %}

<!-- Modal to display delete view -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!-- Form goes here -->
        </div>
    </div>
</div>

<div class="container">
    <div class="row mt-3 mb-5 m-md-5">
        <div class="col-lg-9 box-shadow m-auto transparent-gray">
            <div class="modal-header">
                <h3 class="modal-title">{{ quiz.title }}
                </h3>
                <!-- Cancel button -->
                <a href="../../" class="btn-close" aria-label="Close"></a>
            </div>
            <!-- Quiz info -->
            <div class="me-3 d-flex align-items-center justify-content-end">
                <h5 class="m-1 ms-2 p-1">Status:</h5>
                <a href="{% url 'quiz:toggle' quiz.slug %}"
                    class="btn py-0">{% if quiz.status == 0 %}Draft{% else %}Approved{% endif %}</a>
            </div>
            <div class="d-flex flex-col m-md-2 p-1 align-items-baseline rounded bg-white shadow">
                <div class="m-1 p-1 w-100 rounded">
                    <h6 class="p-1 highlight rounded">Description:</h6>
                    <h6 class="ms-2 my-0 flex-grow-1">{{ quiz.description }}</h6>
                </div>
            </div>
            <div class="d-flex flex-col m-md-2 p-1 align-items-baseline rounded bg-white shadow">
                <div class="m-1 p-1 w-100 rounded">
                    <h6 class="p-1 highlight rounded">Category:</h6>
                    <h6 class="ms-2 my-0 flex-grow-1">{{ quiz.category }}</h6>
                </div>
                <div class="m-1 p-1 w-100 rounded">
                    <h6 class="p-1 highlight rounded">Image:</h6>
                    {% if 'placeholder' not in quiz.featured_image.url %}
                    <h6 class="ms-2 my-0 flex-grow-1"><img src="{{ quiz.featured_image.url }}" class="img-thumbnail" alt="quiz featured image"></h6>
                    {% else %}
                    <h6 class="ms-2 my-0 flex-grow-1">None</h6>
                    {% endif %}
                </div>
            </div>
            <div class="modal-footer mt-3">
                <div class="d-flex col-12 flex-row justify-content-end align-items-center">
                    <div>
                        <a href="{% url 'quiz:edit_quiz' quiz.slug %}" class="btn">Edit quiz</a>
                    </div>
                </div>
            </div>
            <div>
                <div class="modal-body m-md-2  bg-light shadow">
                    <h5 class="py-1">Quiz questions: {{ quiz.questions.all.count }}</h5>
                <ol>
                    {% for question in quiz.questions.all %}
                    <li class="highlight rounded ms-0">
                        <div class="d-flex justify-content-between my-2 m-md-2 p-2 ms-0">
                            {% if question.status == 0 %}
                            <div class="text-secondary">{{ question.body }}<span class="ms-2 small-caps">(Draft)</span></div>
                            {% else %}
                            <div>{{ question.body }}</div>
                            {% endif %}
                                    <ul class="d-flex list-unstyled mt-auto justify-content-between">
                                        <li><a href="{% url 'quiz:quiz_question_details' quiz.slug question.id %}" class="text-dark bs-modal" title="Details">
                                            <i class="fas fa-info-circle mx-2 icon"></i></a></li>
                                        <li><a href="{% url 'quiz:remove_question' quiz.slug question.pk %}" title="Remove from quiz">
                                            <i class="fas fa-times-circle mx-2 icon"></i></a></li>
                                    </ul>
                                </div>
                    </li>
                    {% endfor %}
                </ol>
                </div>
                <div class="modal-footer mt-3">
                    <div class="d-flex col-12 flex-row justify-content-end align-items-center">
                        <div>
                            <a href="{% url 'quiz:add_question_in_quiz' quiz.slug %}" class="btn">Add new question</a>
                        </div>
                    </div>
                </div>

                <div class="modal-body m-md-2 bg-light shadow">
                    <h5>Other questions available in this category: </h5>
                    <div>
                        {% if available_questions %}
                        <ul class="list-unstyled">
                            {% for question in available_questions %}
                            <li class="rounded highlight"> 
                            <div class="d-flex justify-content-between my-2 m-md-2 p-2 ">
                                {% if question.status == 0 %}
                                <div class="text-secondary">{{ question.body }}<span class="ms-2 small-caps">(Draft)</span></div>
                                {% else %}
                                <div>{{ question.body }}</div>
                                {% endif %}
                                        <ul class="d-flex list-unstyled mt-auto justify-content-between">
        
                                            <li><a href="{% url 'quiz:quiz_question_details' quiz.slug question.pk %}" class="text-dark bs-modal" title="Details">
                                                <i class="fas fa-info-circle mx-2 icon"></i></a></li>
                                            <li><a href="{% url 'quiz:add_question' quiz.slug question.pk %}" title="Add to quiz">
                                                <i class="fas fa-plus mx-2 icon"></i></a></li>
                                        </ul>
                            </div>
                            </li>
                            {% endfor %}
                        </ul>
                        {% else %}
                        <p>There are currently no other questions available in this category.</p>
                    {% endif %}
                    </div>
                </div>
                <div class="modal-footer mt-3">
                    <div class="">
                        <a data-form-url="{% url 'quiz:delete_quiz' quiz.slug %}" class="delete-quiz btn" aria-label="Delete" title="Delete">Delete</a>
                        <a href="{% url 'quiz:manage_quizzes' %}" class="btn" aria-label="Save">OK</a>   
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}