categories/urls.py
"""Urls for categories app"""
from django.urls import path
from categories.views import (
    AddCategoryView,
    CategoriesListView,
    EditCategoryView,
    DeleteCategoryView,
)

app_name = 'categories'
urlpatterns = [
    path('categories/', CategoriesListView.as_view(),
         name='manage_categories'),
    path('categories/add_new_category/', AddCategoryView.as_view(),
         name='add_category'),
    path('categories/edit_category/<int:pk>/', EditCategoryView.as_view(),
         name='edit_category'),
    path('categories/delete_category/<int:pk>/', DeleteCategoryView.as_view(),
         name='delete_category'),
    ]

questions/urls.py
"""Urls for questions app"""
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('questions/', views.search, name='manage_questions'),
    path('questions/<int:pk>/details/', views.QuestionDetailsView.as_view(),
         name='question_details'),
    path('questions/add_new_question/', views.CreateQuestionView.as_view(),
         name='add_new_question'),
    path('questions/<int:pk>/edit_question/', views.EditQuestionView.as_view(),
         name='edit_question'),
    path('questions/delete_question/<int:pk>/', views.DeleteQuestionView.as_view(),
         name='delete_question'),
    path('questions/<int:pk>/toggle/', views.toggle_question_status,
         name='toggle_question'),
    path('questions/<int:pk>/add_option/', views.CreateOptionView.as_view(),
         name='add_option'),
    path('questions/<int:pk>/edit_option/', views.EditOptionView.as_view(),
         name='edit_option'),
    path('questions/<int:pk>/delete_option/', views.DeleteOptionView.as_view(),
         name='delete_option'),
    path('questions/<int:pk>/edit_question_text/',
         views.EditQuestionText.as_view(), name='edit_question_text'),
    path('questions/<int:pk>/edit_question_quiz/',
         views.EditQuestionQuiz.as_view(), name='edit_question_quiz'),
    path('questions/<int:pk>/edit_question_feedback/',
         views.EditQuestionFeedback.as_view(), name='edit_question_feedback'),
    path('questions/<int:pk>/edit_question_category/',
         views.EditQuestionCategory.as_view(), name='edit_question_category'),
    path('questions/<int:pk>/edit_question_image/',
         views.EditQuestionImage.as_view(), name='edit_question_image'),
]

quiz/urls.py
"""Urls for quiz app"""
from django.urls import path
from quiz import views

app_name = 'quiz'
urlpatterns = [
    path('', views.welcome_page_view, name='home'),
    path('quizzes/', views.QuizListView.as_view(), name='manage_quizzes'),
    path('quizzes/add_quiz/', views.CreateQuizView.as_view(), name='add_quiz'),
    path('quizzes/<slug:slug>/details/', views.QuizDetailsView.as_view(),
         name='quiz_details'),
    path('quizzes/<slug:slug>/edit_quiz/', views.EditQuizView.as_view(),
         name='edit_quiz'),
    path('quizzes/<slug:slug>/delete_quiz/', views.DeleteQuizView.as_view(),
         name='delete_quiz'),
    path('quizzes/<slug:slug>/toggle/', views.toggle_status, name='toggle'),
    path('quizzes/<slug:slug>/<int:pk>/remove_question/',
         views.remove_question_from_quiz, name='remove_question'),
    path('quizzes/<slug:slug>/<int:pk>/add_question/',
         views.add_question_to_quiz, name='add_question'),
    path('quizzes/add_category', views.AddCategoryInQuizView.as_view(),
         name='add_category_in_quiz'),
    # paths for views managing questions
    path('quizzes/<slug:slug>/add_question/',
         views.CreateQuestionInQuizView.as_view(),
         name='add_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_question/',
         views.DeleteQuestionInQuizView.as_view(),
         name='delete_question_in_quiz'),
    # paths for views for editing question elements when accessed from quiz
    path('quizzes/<slug:slug>/<int:pk>/edit_question/',
         views.EditQuestionInQuizView.as_view(), name='edit_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_text',
         views.EditQuestionText.as_view(), name='edit_question_text_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_quiz',
         views.EditQuestionQuiz.as_view(), name='edit_question_quiz_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_feedback',
         views.EditQuestionFeedback.as_view(),
         name='edit_question_feedback_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_category',
         views.EditQuestionCategory.as_view(),
         name='edit_question_category_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_image',
         views.EditQuestionImage.as_view(),
         name='edit_question_image_in_quiz'),
    # paths for viees managing options
    path('quizzes/<slug:slug>/<int:pk>/add_option/',
         views.CreateOptionInQuizView.as_view(), name='add_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_option/',
         views.EditOptionInQuizView.as_view(), name='edit_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_option/',
         views.DeleteOptionQuizView.as_view(), name='delete_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/details/',
         views.QuestionDetailsInQuizView.as_view(),
         name='quiz_question_details'),
    ]

results/urls.py
"""Urls for results app"""
from django.urls import path
from . import views

app_name = 'results'
urlpatterns = [
    path('quizzes/<slug:slug>/take_quiz/', views.TakeQuizView.as_view(),
         name='take_quiz'),
    path('quizzes/<slug:slug>/assessment-<int:pk>/results/',
         views.AssessmentView.as_view(), name='assessment_details'),
    ]

teaze/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('quiz.urls'), name='quiz_urls'),
    path('', include('results.urls'), name='results_urls'),
    path('', include('questions.urls'), name='questions_urls'),
    path('', include('categories.urls'), name='categories_urls'),
]

quiz/models.py
"""Quiz model and methods"""
from django.urls import reverse
from django.db import models
from django.template.defaultfilters import slugify
from cloudinary.models import CloudinaryField
from categories.models import Category
# import random


STATUS = ((0, 'Draft'), (1, 'Published'))


class Quiz(models.Model):
    """Create Quiz object"""

    title = models.CharField(max_length=200, unique=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT,
                                 related_name='quiz')
    slug = models.SlugField(max_length=200, unique=True)
    description = models.CharField(max_length=300, blank=True)
    # number_of_questions = models.IntegerField()
    featured_image = CloudinaryField('image', default='placeholder',
                                     blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        """Set plural name to show in admin"""
        verbose_name_plural = "Quizzes"

    def get_questions(self):
        """Get all questions assigned to thie quiz"""
        # Randomisation of quesitons taken from Pyplane tutorial:
        # https://www.youtube.com/watch?v=T9xOjVJI1rg
        # questions = list(self.questions.all())
        # random.shuffle(questions)
        # return questions[:self.num_of_questions]
        return self.questions.all()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Quiz, self).save(*args, **kwargs)

    def __str__(self):
        """Quiz string method"""
        return self.title

    def toggle_status(self, *args, **kwargs):
        """"Togge quiz status."""
        if self.status != 0:
            self.status = 0
        else:
            self.status = 1
        self.save()
        super(Quiz, self).save(*args, **kwargs)

    def get_absolute_url(self):
        """Get absolute url"""
        return reverse('quiz:quiz_details', kwargs={"slug": self.slug})

templates/base.html
{% load static %}
{% load quiz_extras %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Metadata -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Taze web based application to create and deliver quizzes and tests.">
    <title>Teaze</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- Bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!-- Top Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark flex-nowrap">
        <!-- Main navbar container -->
        <div class="container-fluid">
            <!-- Teaze logo -->
            <a href="{% url 'quiz:home' %}">
            <img id="logo" class="img-fluid" src="https://res.cloudinary.com/dcslh2m3b/image/upload/v1645780117/teaze/teaze-logo-large_girzyw.png" alt="Teaze logo">
            </a>
            <!-- Menu -->
            <div class="d-flex flex-wrap mr-auto me-2 pb-0 lh-1 justify-content-end">
                <!-- Collapsed menu button -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Menu item -->
                <div class="collapse navbar-collapse mr-auto mt-2" id="navbarSupportedContent">
                    <ul class="navbar-nav me-2 mb-2 mb-lg-0 align-items-end">
                        {% if user.is_authenticated %}
                        <!-- Admin menu -->
                            {% if request.user|has_group:"Admin" %}
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page"
                                    href="{% url 'quiz:home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/quizzes/' %}active{% endif %}"
                                    href="{% url 'quiz:manage_quizzes' %}">Manage quizzes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/questions/' %}active{% endif %}"
                                    href="{% url 'questions:manage_questions' %}">Manage questions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/categories/' %}active{% endif %}"
                                    href="{% url 'categories:manage_categories' %}" tabindex="-1">Manage categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/accounts/logout/' %}active{% endif %}"
                                    href="{% url 'account_logout' %}">Log out</a>
                            </li>
                            <!-- Standard user menu -->
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/accounts/signin/' %}active{% endif %}"
                                    href="{% url 'account_logout' %}">Log out</a>
                            </li>
                            {% endif %}
                        {% else %}
                        <!-- Anonymous user menu -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- Current user info -->
    {% if user.is_authenticated %}
    <div class="my-0 px-4 pb-1 text-lightgray text-smaller d-flex justify-content-end bg-dark">Current user:&nbsp;<span
            class="small-caps">{{ request.user }}</span></div>
    {% endif %}
    <!-- Alerts -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2 my-3 alert-success rounded-5 border-dark">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Main content -->
    <main class="flex-shrink-0 main-bg">
        <div class="py-md-2 pb-5 my-auto mx-2">
            {% block content %}
            <!-- Content goes here -->
            {% endblock content %}
        </div>
    </main>

    <!-- Footer -->
    <footer class="mt-5">
        <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 mb-0">
                <span class="ms-2 text-muted justify-content-sm-center">© 2022 kokoMedia</span>
            <!-- </div> -->
                        <ul class="nav col-md-4 justify-content-end px-3 list-unstyled d-flex">
                <li class="ms-3"><a class="text-muted" href="#" title="twitter" aria-label="twitter"><i
                            class="fab fa-twitter"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#" title="instagram" aria-label="instagram"><i
                            class="fab fa-instagram"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#" title="facebook" aria-label="facebook"><i
                            class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
    </footer>

    <!-- Bootstrap script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/3241ed12ad.js" crossorigin="anonymous"></script>
    <!-- django-bootstrap-modal-forms script -->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- Custom script -->
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load quiz_extras %}

{% block content %}

{% if user.is_authenticated %}
<!-- Admin user's view -->
    {% if request.user|has_group:"Admin" %}
    <!-- Modals -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <!-- Form goes here -->
            </div>
        </div>
    </div>
    <!-- Dashboard main container -->
    <div class="container px-0 px-md-4 mb-3" id="custom-cards">
        <h2 class="pb-2 border-bottom">Dashboard</h2>
        <!-- Quizzes -->
        <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-md-5">
            <div class="col"><a href="{% url 'quiz:manage_quizzes' %}" class="linked">
                    <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg">
                        <div class="d-flex flex-column h-100 p-4 p-md-5 pb-3 text-white text-shadow-1">
                            <h5 class="pt-3 mt-2 mb-4 lh-1 fw-bold border-bottom">Quizzes</h5>
                            <h6 class="card-title">Published: <small>{{ quiz_published_count }}</small></h6>
                            <h6 class="card-title">Drafts: <small>{{ quiz_draft_count }}</small></h6>
                            <!-- Ad new and manage buttons -->
                            <ul class="d-flex list-unstyled mt-auto justify-content-end">
                                <li class="d-flex align-items-center me-3">
                                    <a href="{% url 'quiz:add_quiz' %}" class="linked"><i class="fas fa-plus"></i>
                                        <small class="">New</small></a>
                                </li>
                                <li class="d-flex align-items-center">
                                    <a href="{% url 'quiz:manage_quizzes' %}" class="linked"><i
                                            class="fas fa-book-open"></i>
                                        <small class="p-md-2">Manage</small></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </a>
            </div>
            <!-- Questions -->
            <div class="col">
                <a href="{% url 'questions:manage_questions' %}" class="linked">
                    <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg">
                        <div class="d-flex flex-column h-100 p-4 p-md-5 pb-3 text-white text-shadow-1">
                            <h5 class="pt-3 mt-2 mb-4 lh-1 fw-bold border-bottom">Questions</h5>
                            <h6 class="card-title">Published: <small>{{ question_published_count }}</small></h6>
                            <h6 class="card-title">Drafts: <small>{{ question_draft_count }}</small></h6>
                            <!-- Ad new and manage buttons -->
                            <ul class="d-flex list-unstyled mt-auto justify-content-end">
                                <li class="d-flex align-items-center me-3">
                                    <a href="{% url 'questions:add_new_question' %}" class="linked"><i
                                            class="far fa-edit"></i>
                                        <small class="p-md-2">New</small></a>
                                </li>
                                <li class="d-flex align-items-center">
                                    <a href="{% url 'questions:manage_questions' %}" class="linked"><i
                                            class="fas fa-book-open"></i>
                                        <small class="p-md-2">Manage</small></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </a>
            </div>
            <!-- Categories -->
            <div class="col">
                <a href="{% url 'categories:manage_categories' %}" class="linked">
                    <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg">
                        <div class="d-flex flex-column h-100 p-4 p-md-5 pb-3 text-white text-shadow-1">
                            <h5 class="pt-3 mt-2 mb-4 lh-1 fw-bold border-bottom">Categories</h5>
                            <h6 class="card-title">Total: <small>{{ categories_count }}</small></h6>
                            <!-- Ad new and manage buttons -->
                            <ul class="d-flex list-unstyled mt-auto justify-content-end">
                                <li class="d-flex align-items-center me-3">
                                    <a data-form-url="{% url 'categories:add_category' %}" class="add-category linked"
                                        alt="Add category"><i class="far fa-edit"></i>
                                        <small class="p-md-2">New</small></a>
                                </li>
                                <li class="d-flex align-items-center">
                                    <a href="{% url 'categories:manage_categories' %}" class="linked"><i
                                            class="fas fa-book-open"></i>
                                        <small class="p-md-2">Manage</small></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    {% else %}
    <!-- Standard user's dashboard view-->
    <div class="container px-0 px-md-4 mb-3" id="custom-cards">
        <h2 class="pb-2 border-bottom">Your quizzes</h2>

        <div
            class="row row-cols-1 {% if quiz_list.count < 3 %}row-cols-lg-{{quiz_list.count}}{% else %}row-cols-lg-3{% endif %} h-100 align-items-stretch g-4 g-4 py-md-5">
            {% for quiz in quiz_list %}
            <div class="col">
                <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow">
                    <div class="d-flex flex-column h-100 p-4 p-md-5 pb-3 text-white text-shadow-1">
                        <h4 class="modal-header">{{ quiz.title }}</h4>
                        <div class="modal-body">
                            <h5>Category: <small>{{ quiz.category }}</small></h5>
                            <p class="text-smaller">{{ quiz.description }}</p>
                            <ul class="d-flex list-unstyled mt-auto justify-content-end">
                                <!-- Check if the user completed the quiz -->
                                {% if quiz in completed_quizzes %}
                                <!-- If yes display 'Completed' with a checkbox and a link to see results -->
                                <li class="d-flex align-items-center me-3">Completed<i class="fas fa-check-square ms-3"></i>
                                </li>
                                <li class="d-flex align-items-center me-3 btn"><a class="linked"
                                        href="{% url 'results:assessment_details' assessment.quiz.slug assessment.pk %}">
                                        Results</a></li>
                                <!-- if not completed, show button with link to take quiz -->
                                {% else %}
                                <li><a href="{% url 'results:take_quiz' quiz.slug %}" class="btn">Start Quiz</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endif %}
{% endblock %}