categories/urls.py
"""Urls for categories app"""
from django.urls import path
from categories.views import (
    AddCategoryView,
    CategoriesListView,
    EditCategoryView,
    DeleteCategoryView,
)

app_name = 'categories'
urlpatterns = [
    path('categories/', CategoriesListView.as_view(),
         name='manage_categories'),
    path('categories/add_new_category/', AddCategoryView.as_view(),
         name='add_category'),
    path('categories/edit_category/<int:pk>/', EditCategoryView.as_view(),
         name='edit_category'),
    path('categories/delete_category/<int:pk>/', DeleteCategoryView.as_view(),
         name='delete_category'),
    ]

quiz/urls.py
"""Urls for quiz app"""
from django.urls import path
from quiz import views

app_name = 'quiz'
urlpatterns = [
    path('', views.welcome_page_view, name='home'),
    path('quizzes/', views.QuizListView.as_view(), name='manage_quizzes'),
    path('quizzes/add_quiz/', views.CreateQuizView.as_view(), name='add_quiz'),
    path('quizzes/<slug:slug>/details/', views.QuizDetailsView.as_view(),
         name='quiz_details'),
    path('quizzes/<slug:slug>/edit_quiz/', views.EditQuizView.as_view(),
         name='edit_quiz'),
    path('quizzes/<slug:slug>/delete_quiz/', views.DeleteQuizView.as_view(),
         name='delete_quiz'),
    path('quizzes/<slug:slug>/toggle/', views.toggle_status, name='toggle'),
    path('quizzes/<slug:slug>/<int:pk>/remove_question/',
         views.remove_question_from_quiz, name='remove_question'),
    path('quizzes/<slug:slug>/<int:pk>/add_question/',
         views.add_question_to_quiz, name='add_question'),
    path('quizzes/add_category', views.AddCategoryInQuizView.as_view(),
         name='add_category_in_quiz'),
    # paths for views managing questions
    path('quizzes/<slug:slug>/add_question/',
         views.CreateQuestionInQuizView.as_view(),
         name='add_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_question/',
         views.DeleteQuestionInQuizView.as_view(),
         name='delete_question_in_quiz'),
    # paths for views for editing question elements when accessed from quiz
    path('quizzes/<slug:slug>/<int:pk>/edit_question/',
         views.EditQuestionInQuizView.as_view(), name='edit_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_text',
         views.EditQuestionText.as_view(), name='edit_question_text_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_quiz',
         views.EditQuestionQuiz.as_view(), name='edit_question_quiz_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_feedback',
         views.EditQuestionFeedback.as_view(),
         name='edit_question_feedback_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_category',
         views.EditQuestionCategory.as_view(),
         name='edit_question_category_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_image',
         views.EditQuestionImage.as_view(),
         name='edit_question_image_in_quiz'),
    # paths for viees managing options
    path('quizzes/<slug:slug>/<int:pk>/add_option/',
         views.CreateOptionInQuizView.as_view(), name='add_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_option/',
         views.EditOptionInQuizView.as_view(), name='edit_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_option/',
         views.DeleteOptionQuizView.as_view(), name='delete_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/details/',
         views.QuestionDetailsInQuizView.as_view(),
         name='quiz_question_details'),
    ]

teaze/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('quiz.urls'), name='quiz_urls'),
    path('', include('results.urls'), name='results_urls'),
    path('', include('questions.urls'), name='questions_urls'),
    path('', include('categories.urls'), name='categories_urls'),
]

categories/models.py
"""Construct category"""
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Category(models.Model):
    """Create category"""

    name = models.CharField(max_length=50, unique=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        """Set plural name for Category"""
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        """Define string value for object"""
        return self.name

    def get_absolute_url(self):
        """Set absolute url"""
        return reverse('categories:manage_categories')

categories/forms.py
"""Form to create questions and answers"""
from django import forms
from django.contrib.auth.models import User
from bootstrap_modal_forms.mixins import (
    PopRequestMixin,
    CreateUpdateAjaxMixin
)
from .models import Category


class NewCategoryForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    """Category form class."""

    class Meta:
        """Set fields to show in the form."""
        model = Category
        fields = (
            'name',
            )

    def save(self, commit=False):
        """
        Overwrites the default save method to add current user as author and
        prevents Ajax error: 'NoneType' object has no attribute 'META'
        """
        if not self.request.is_ajax():
            instance = super(CreateUpdateAjaxMixin, self).save(commit=commit)
            instance.author = User.objects.get(pk=self.request.user.pk)
            instance.save()
        else:
            instance = super(CreateUpdateAjaxMixin, self).save(commit=False)
        return instance

categories/views.py
"""Views to manage categories - CRUD"""
from django.urls import reverse_lazy
from django.views.generic import ListView
# views provided by django-bootstrap-modal-forms
from bootstrap_modal_forms.generic import (
    BSModalCreateView,
    BSModalUpdateView,
    BSModalDeleteView
)
from quiz.models import Quiz
from .forms import NewCategoryForm
from .models import Category


class AddCategoryView(BSModalCreateView):
    """Add new category."""

    template_name = 'categories/add_category.html'
    form_class = NewCategoryForm
    success_message = 'Success: Category was created.'
    success_url = reverse_lazy('categories:manage_categories')


class EditCategoryView(BSModalUpdateView):
    """Edit category."""

    model = Category
    template_name = 'categories/edit_category.html'
    form_class = NewCategoryForm
    success_message = 'Success: Category was updated.'
    success_url = reverse_lazy('categories:manage_categories')


class DeleteCategoryView(BSModalDeleteView):
    """Delete category."""

    model = Category
    success_message = 'Success: Category was deleted.'
    success_url = reverse_lazy('categories:manage_categories')


class CategoriesListView(ListView):
    """List all available categories."""
    model = Category
    template_name = 'categories/manage_categories.html'

    def get_context_data(self, **kwargs):
        """Get list of categories used in quizzes as additional context data"""
        context = super(CategoriesListView, self).get_context_data(**kwargs)
        # Get all categories used in quizzes
        quizzes = Quiz.objects.all()
        protected_categories = []

        for quiz in quizzes:
            protected_categories.append(quiz.category)
            print(protected_categories)

        context['protected_categories'] = protected_categories
        return context

categories/templates/categories/add_category.html
{% load widget_tweaks %}
<!-- Form to add new category. -->
<form method="POST">
    {% csrf_token %}

    <div class="modal-header">
        <h3 class="modal-title">Add category</h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" placeholder=field.label %}
            <div class="{% if field.errors %} invalid{% endif %}">
                {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        </div>
        {% endfor %} 
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn">Save</button>
    </div>
</form>

categories/templates/categories/category_confirm_delete.html
{% load widget_tweaks %}
<!-- Form with category details -->
<form method="POST">
  {% csrf_token %}
  <!-- Modal content injected into the modal div in the main manage categories view  -->
  <div class="modal-header">
    <h3 class="modal-title">Delete category</h3>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <div class="modal-body">
  <!-- Check if category is used in a quiz or question; if yes, deletion is not possible (to handle ProtectedError) -->
  {% if protected %}
        <p>{{ protected_message|safe }}</p>
  </div>
  <div class="modal-footer">
    <button type="button" data-bs-dismiss="modal" class="btn" aria-label="Ok">OK</button>
  </div>
  <!-- If category not protected, ask to confirm deletion. -->
  {% else %}
  <div class="modal-body">
    <p>Are you sure you want to delete category 
      <strong>{{ category.name }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn">Delete</button>
  </div>
  {% endif %}
</form>

categories/templates/categories/edit_category.html
{% load widget_tweaks %}
<!-- Form with category details that is being edited. -->
<form method="POST">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Edit category</h3>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>

</form>

categories/templates/categories/manage_categories.html
{% extends 'base.html' %}
{% load quiz_extras %}

{% block content %}

<!-- Modal for edit and delete forms -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!-- Form goes here -->
        </div>
    </div>
</div>

<!-- Main container for cards -->
<div class="container px-0 px-md-4 py-2 pb-5 py-md-5" id="custom-cards">
    <div class="d-flex justify-content-between border-bottom">
        <div>
            <h2 class="pb-2">Categories</h2>
        </div>
        <div class="me-3">
            <h3 class="pb-2"><a data-form-url="{% url 'categories:add_category' %}" class="add-category text-dark linked">Add new<i class="fas fa-plus ms-1 ms-md-3"></i></a></h3>
        </div>

    </div>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-md-5">
        <!-- loop through the database to find all categories and create card for each -->
        {% for category in category_list %}
        <div class="col pt-2">
            <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow">
                <div class="d-flex flex-column h-100 p-4 p-md-5 pb-3 text-white text-shadow-1">
                    <h5 class="pt-3 mt-2 mb-4 lh-1 fw-bold border-bottom">{{ category.name }}</h5>
                    <!-- List element with Edit and Delete links and icons -->
                    <ul class="d-flex list-unstyled mt-auto justify-content-end">
                        <li class="d-flex align-items-center me-3">
                            <a data-form-url="{% url 'categories:edit_category' category.id %}" class="edit-category bs-modal linked">
                                <small class="p-2">Edit</small><i class="fas fa-edit"></i></a>
                        </li>
                        {% if category in protected_categories %}
                        <li class="d-flex align-items-center">
                            <a class="linked" aria-label="Category used in quiz and cannot be deleted">
                                <small class="p-2 text-decoration-line-through" data-bs-toggle="tooltip" data-bs-placement="right" title="Category used in quiz and cannot be deleted">
                                    Delete</small><i class="fas fa-exclamation-circle"></i></a>
                            </li>
                        {% else %}
                        <li class="d-flex align-items-center">
                        <a data-form-url="{% url 'categories:delete_category' category.pk %}"  class="delete-category bs-modal linked" aria-label="Delete category">
                            <small class="p-2">Delete</small><i class="fas fa-trash"></i></a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}